"""Given a DNA dataset Count how many nucleotides A,T,G,C contained in the dataset"""

DNA = "ACCACCACTTATTAAACCAAACCGACGATAAGTTTCGAGGGGATGTCACGTACGCATGTGGTGATACTGGTCATCTTTAAAACTAATATGGAGACAGCGGCTTTAATGCTCGCAAGGCCTCTCGCTTTTAGTTCGTACGGCTGGTAGGAAGCCAGCGCTGTTGAGCCTACAGTGAAATGCTCCTCCCCTTTTCCGTGCGATCGAAAAGTTCTGCGAATTGTTCACGAAGTAGCATTTGTACACACTACGTCTGGGGCACCCAACTCAGTCTCCATCGAATGCGATTAAACGGTGTATTAACACCGGTCTGACAGCTGGGAAGAAAACACACTCAGCAGAGTCTTGTACACTCCTAAAAGCAGAAGCCTGCCTTTTTGCGTTCGACTGCTACTGGTGACGTTCAGCTGGTAGCAGATTTGTATCCTACCAGTGAGCACGATCTTCCATGCCCTCCAATTGCCTTGAGTATATTAGTCCCCTGTGGGTGGCATTTACACAATCAGCGCTGAATATTTGTCACAGAATCTCGAGTGGGGTGCATGGACCGGCCTTTTCACCGGCCCTTGACATGCCGACTTGCGAATCCGACCCACAATTCTTTCGCAAGTTCGACTTTGTAAGGTTGCGGTGCCGCAACTGGATCGATGGGCGATGTGTGGGCACTGGCCCGTGAGTCCTGGTTAATCGGATCCGGGCGTTTCCTGCAACTGCTGTGAATACTACAATCTCATGTGGGAGCGTTACGGATAGCTAACCCAGATCTGTGTGCAGTCCATATAATCGTTTCGCAGTGAAGTTTATTTTACGTGTGCAGCTGAAGACGCGCATCGGTTCACCGT"

def Nucleotide_counter(dataset):
    Adenine = 0
    Thymine = 0
    Guanine = 0
    Cytosine = 0
    for n in dataset:
        if n == "A":
            Adenine+=1
        if n == "C":
            Cytosine+=1
        if n == "G":
            Guanine+=1
        if n == "T":
            Thymine+=1
        
        
            
    print(Adenine, Cytosine, Guanine, Thymine)


Nucleotide_counter(DNA)
