"""In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.
The reverse complement of a DNA string (s)
is the string (sc) formed by reversing the symbols of (s), then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC")."""


"""Inport module"""
from Bio.Seq import Seq

DNA = "ACAGTGATTCCATGCGCTCGGGCTTCCTGCAAAGACTGCGATGCAAACCGGACAACGACTCCACCTAGGTCGCATGATCTTGACGCATGGGGTGACGAACATAAATTTAATGTAAAAGAGCTCATATTACCTTCTAGCAGTGAGGTGTCTTCCAGTACGACAAGGGTCAGGACCCAAAAAAATTGCCCTCCCCTAGAGGTCGAGGCTACGAGCAATTGCACCCAGACATTCACGTAGCATCGGCTGCGTCATAGGGATGAACGGCACTGCAGTGCCACTCTGTGAGAAACCTTTTAGGTAATTATCAATCGTAGAGACTACCCATAATCGGAAGTAGGGTACGGTGATGGGTATCGGTTTAGGAGGGGTGTGACACGCTAAATTTACTAAGGAGAAAAACCCTTATGGTGTGAGTGGCTTTAGGGAAGTAGGCATGCGACGCGGGGAGGTTCGCTACTGGTAAGATTCCTTACGTCACCATGTAAACCACCACGTTGGAGGGCTTGTTTGTTGAGGCTTAGGACTAGGACAAAGTCAAGCCTGGCGGTTGGTGGGGCCAATGTCAATCATCCAGCACGATTGGTGTGGAAGCGAGTGAACCAGTGACGACCTAAGCGAGAGAGCACCCTGACTGGCCGACCCGGCTGTGACACTCAATTTCCGGAACTCGCTTTTCCATGTACTAACGAAAGTGACTCGAAGCGAGTTGCAGGGGGACGTATAGACACGCAAAAGTACGTTATTAACTATGAGTAACGGCGCTAGTGTCAAAATCCTCCAGCCCGTGTGTCGAGAACCCGATGATGAGGTATGGCGCCGATCAGAGGCCGGATTACAAAGTAGGATG"

def reverse_complement(dataset):
    seq = Seq(dataset)
    reverse = seq.reverse_complement()
    print (reverse)

reverse_complement(DNA)