"""In DNA responserings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.
The reverse complement of a DNA string (s)
is the string (sc) formed by reversing the symbols of (s), then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC")."""

# with open("rosalind_revc.txt", "r") as dna:
#     dna = "".join(dna.readlines())
#     comp = {"A": "T", "C": "G", "G": "C", "T": "A"} 
#     for i in reversed(dna):
#         print("".join(comp[i]), end="")


DNA = "ACAGTGATTCCATGCGCTCGGGCTTCCTGCAAAGACTGCGATGCAAACCGGACAACGACTCCACCTAGGTCGCATGATCTTGACGCATGGGGTGACGAACATAAATTTAATGTAAAAGAGCTCATATTACCTTCTAGCAGTGAGGTGTCTTCCAGTACGACAAGGGTCAGGACCCAAAAAAATTGCCCTCCCCTAGAGGTCGAGGCTACGAGCAATTGCACCCAGACATTCACGTAGCATCGGCTGCGTCATAGGGATGAACGGCACTGCAGTGCCACTCTGTGAGAAACCTTTTAGGTAATTATCAATCGTAGAGACTACCCATAATCGGAAGTAGGGTACGGTGATGGGTATCGGTTTAGGAGGGGTGTGACACGCTAAATTTACTAAGGAGAAAAACCCTTATGGTGTGAGTGGCTTTAGGGAAGTAGGCATGCGACGCGGGGAGGTTCGCTACTGGTAAGATTCCTTACGTCACCATGTAAACCACCACGTTGGAGGGCTTGTTTGTTGAGGCTTAGGACTAGGACAAAGTCAAGCCTGGCGGTTGGTGGGGCCAATGTCAATCATCCAGCACGATTGGTGTGGAAGCGAGTGAACCAGTGACGACCTAAGCGAGAGAGCACCCTGACTGGCCGACCCGGCTGTGACACTCAATTTCCGGAACTCGCTTTTCCATGTACTAACGAAAGTGACTCGAAGCGAGTTGCAGGGGGACGTATAGACACGCAAAAGTACGTTATTAACTATGAGTAACGGCGCTAGTGTCAAAATCCTCCAGCCCGTGTGTCGAGAACCCGATGATGAGGTATGGCGCCGATCAGAGGCCGGATTACAAAGTAGGATG"

def reverse_complement(dataset):
    reverse = dataset.replace('A', 't').replace('T', 'a').replace('C', 'g').replace('G', 'c').upper()[::-1]
    print (reverse)


reverse_complement(DNA)