"""

Given: Two DNA strings s and t(each of length at most 1 kbp).

Return: All locations of t as a substring of s.

"""

from Bio.Seq import Seq

s = Seq("TGGTGCATGATGTAACACGTAACACCGTGTAAGTAACACGTAACACTACGGGTAACACACATGTAACACCTAGGTGTAACACGTAACACGTAACACCTAAGTAACACAATGCCGTAACACATATTCGTAACACGTAACACGGAGGTAACACTAGTAACACCCTGTTTGTAACACCCGTAACACAAAGTAACACGTAACACACGGTAACACGTAACACTGTAACACTCAGTGTAACACGTAACACTGAGAGGTAACACGTAACACGTAACACCGGGAGTAACACCCCTGACCGGTAACACGGTAACACGGTAACACTTATGCTGTAACACGTAACACGTAACACGTAACACAGTGTAACACGTAAGTAACACAGTAACACCGGTAACACGTAACACCGACTATGAAGTAACACGTAACACATATCAAGTAACACGTAACACGTAACACATAGTGAGGTAACACGTAACACGTAACACCCTGTAACACGTAACACGCAGTAACACGTATACACATGAGTAACACTCAACCGTAACACGTAACACGTAACACATAAACGTGGGTAACACATGGTGGGGTAACACCGAGTAACACGTAACACGTAACACGTCGGTAACACAATGTAACACACGTCGTAACACTTGACAGAGTAACACCCTGGTAACACCGTAACACGTAACACGTAACACCGGTAACACTCACAGTAACACGCGTAACACAGGTAACACTGGTAACACATGTAACACGCCCGCGTAACACGTAACACACATCAGGTAACACAGGTAACACACAGTAACACCGGCGCGAGTAACACGTAACACGTAACACGTAACACCCCGAGTAACACAGTAACACGTTCTGTAACACCAGTAACACGTAACACGGTAACAC")
t = Seq("GTAACACGT")

locations = []
count = 0
loc = 0

while (count < len(s)):
    loc = s.find(t, start=count)
    if (loc > 0):
        count = loc + 1
        locations.append(loc + 1)
    else:
        count = count + 1
    
print(' '.join(map(str,locations)))


